# Generated by Django 4.2.4 on 2023-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_luogo', models.CharField(max_length=50)),
                ('immagine', models.ImageField(upload_to='')),
                ('descrizione_luogo', models.TextField()),
                ('citta', models.BooleanField(default=True)),
                ('sintesi', models.CharField(blank=True, max_length=2000)),
                ('dove', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
