# Generated by Django 4.2.4 on 2023-10-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sintesi',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
