# Generated by Django 4.2.4 on 2023-10-05 17:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0002_alter_place_sintesi'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='autore',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
