# Generated by Django 4.2.4 on 2023-10-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0003_place_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='autore',
            field=models.CharField(max_length=200),
        ),
    ]
