# Generated by Django 4.2.4 on 2023-10-06 07:42

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0005_alter_place_autore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='descrizione_luogo',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
