# Generated by Django 4.2.4 on 2023-10-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0008_city_placetovisit_delete_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placetovisit',
            old_name='descrizione_luogo',
            new_name='descrizione',
        ),
    ]
