# Generated by Django 4.2.4 on 2023-11-01 10:51

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('luoghi', '0009_rename_descrizione_luogo_placetovisit_descrizione'),
    ]

    operations = [
        migrations.AddField(
            model_name='placetovisit',
            name='immagine_45',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='mappa',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='riassunto',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placetovisit',
            name='storia',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
